* RICE

** Themes

Using new theme: Mona
https://www.gnome-look.org/p/1013687/

It is the best looking theme I found. Colors are nice, display of pop up windows, menus, messages is great.

** Icons

- Papirus
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

Also used the Papirus icons for SMPlayer and LibreOffice (see instructions in github page)

One problem with thunderbird tray icon: the default icon for this is a crappy bell, so I had to override it: I found a nice thunderbird icon with alpha channel in google.

** Mouse cursors

I tried really hard to find a nice cursor set, I downloaded some, but none was what I looked for. Sticking up with the default DMZ-Black for now.

** Fonts

Search for these fonts in Google fonts.
- Jura (default)
Set this as the default font for i3 and GTK applications. Nice futuristic look with Greek support. Using the Light version.
- Adel (i3 status bar)
Simple, modern and condensed font with no changes in width, nice to have a concentrated and stable bar.
