* THOUGHTS

** COLLABORATING PARTS

*** NODE.JS (MAIN SERVER)

*** PIRATEBOX ON NODE.JS

*** TIDDLYWIKI ON NODE.JS
TiddlyWiki is used for the webpage interface. To make it suit our purposes we made some changes in the core functions, also created some new functions. The complete path to the core functions is: =/usr/local/lib/node_modules/tiddlywiki/core/modules/widgets=.

Also, we had to include =Socket.io= to its functionality.

- Each keyword and selected material activates the =action-socketSend= function.
This function is used to send messages to the Node.js server using Socket.io.
The function has two fields:
1) The =$type= field, which determines whether the message sent refers to a keyword or a tiddler title. Acceptable values: =key= and =title=
2) The =$val= field, which is either the keyword selected or the tiddlers' title.
The function then creates an object with those two fields, as well as a third field, =url=, which consists of the current URL. This is used as a reference, to not lose the current contents of the page, while updating it with new content.
This object is sent to the server with Socket.io, which emits an event named 'tiddler info'.

- Each material tiddler (currently only in tiddlers containing photos) has a button labeled "Post on PirateBox". This button invoces the function =action-navigate2=, which is an altered version of the core function =action-navigate=.

The function has three fields:
1) The =$id= field, which is the title of the tiddler.
2) The =$path= field, which is the absolute path of the photo on the server.
3) The =$dimension= field, which is used to determine which is the biggest dimension of the photo (width or height). This is used as an abrupt way of displaying landscape and portrait images correctly.

This function navigates us to an altered version of the PirateBox chatroom, by manually changing the value of =window.location.href=, which corresponds to the current URL in JavaScript, by also including a set of parameters to it. The parameters come from the function fields, plus the current URL.
1) The =id= parameter is used to display the title of the picture.
2) The =addr= parameter is a string containing the current URL, and is used so that we can navigate back in the same page from piratebox.
3) The =path= parameter is used to display the actual image.
4) The =dim= parameter is used to display the image correctly, according to its orientation.

This instance of the PirateBox chatroom displays on the side the picture from which we navigated there, instead of the other functions of PirateBox. Also, when we post an entry in the chat, the picture gets posted as well.

- To include Socket.io functionality, we added two system tiddlers:

1) =$:/myJS/include socket.io=: A Javascript statement to include the Socket.io script.

2) =$:/myJS/tiddlySocket=: A Javascript statement to include a custom script. This script contains a function that receives Socket.io messages and updates the current URL.

*** SUPERCOLLIDER

** EXTRA TOOLS

*** SOCKET.IO
Socket.io is used to send and receive messages between the client and the server. Each client can be accessed separately by using it's socket id.

*** OSC-MIN
Osc-min is used to send and receive OSC messages to and from SuperCollider.
