* About the project

The Secret School is a webpage hosted on a Raspberry Pi configured to be an access point, without access to the internet. 


* TECHNICAL ASPECTS

The tools used to create the Secret School are:

- Node.js
- Socket.io
- Express.js
- osc-min
- Pirate Box
- TiddlyWiki
- SuperCollider

** NODE.JS

Node.js is used to create the server for the webpage using JavaScript.

** SOCKET.IO

Socket.io takes care of the communication between the server and the webpage. It is used for two reasons: First, to send a message from the webpage to the server, that will be sent afterwards as an OSC message through osc-min, alongside with information about the client that sent the message. Second, to send private messages from the server to each client.

** PIRATE BOX

   Here is used an alternative version of PirateBox, written in Node.js. The main difference is that it does not create its own network, you have to do it manually. The reason of this choice is that the communication is easier between the main webpage and the PirateBox webpage, and also we gain the possibility to send OSC messages with osc-min. PirateBox serves as the chatroom and also gives the possibility for a client to upload material that will be included in the webpage (under construction).

** TIDDLYWIKI

TiddlyWiki is used for the homepage of the project, due to its navigation layout. Some internal functions had to be modified, and one or two new ones were created, to reach the desired functionality. The new functions provided a connection with the main server with socket.io.

** SUPERCOLLIDER

SuperCollider was used, except of playing a sound, but also as an organizing engine for material - keyword connection. Some dictionaries were created, storing tiddlers titles or sound titles as keys and the corresponding keywords as content. Some functions were written, to receive an OSC message from the WebServer including a keyword or a tiddlers title, and to randomly select a sound and a tiddler related to this keyword. The sound gets played and the tiddler's title is sent back to the server as an OSC message. Also, the trancription of the selected sound is sent to PirateBox to be posted in the chat.

* PURPOSE

The main purpose of the Secret School Project is to create an alternative way of narration, which will be different for each client, in combination with a common experience, via the played sound and the chatroom. Each connected user navigates through the included material using the keywords to trigger random material related to this keyword, or related to the material itself, with a different keyword. Thus, he creates his personal view of the homepage, with unique succession of pictures, texts, videos etc. But also, by doing so, he participates firstly in the creation of a common soundscape, consisting of sound related to his choices, alongside with sounds triggered from the other users, secondly in the formation of an optical poem, which is displayed in the form of a chatroom, where the audio trancriptions are printed, or where you can leave your own message, or even cause a photo to be displayed. The chat output will be projected on a big screen and the audio will be heard from speakers (under construction)
